# Visit https://github.com/lowlighter/metrics#-documentation for full reference
name: Metrics
on:
  # Schedule updates (each hour)
  schedule: [{cron: "0 * * * *"}]
  # Lines below let you run workflow manually and on each commit
  workflow_dispatch:
  push: {branches: Metrics}
jobs:
  github-metrics:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: lowlighter/metrics@latest
        with:
          # Your GitHub token
          # The following scopes are required:
          #  - public_access (default scope)
          #  - repo
          # The following additional scopes may be required:
          #  - read:org      (for organization related metrics)
          #  - read:user     (for user related data)
          #  - read:packages (for some packages related data)
          #  - repo          (optional, if you want to include private repositories)
          token: ${{ secrets.METRICS_TOKEN }}

          # Options
          user: Croc-Prog-github
          template: classic
          base: header, activity, community, repositories
          config_timezone: Europe/Rome
          plugin_achievements: yes
          plugin_achievements_display: detailed
          plugin_achievements_limit: 5
          plugin_achievements_secrets: yes
          plugin_achievements_threshold: X
          plugin_gists: yes
          plugin_isocalendar: yes
          plugin_isocalendar_duration: half-year
          plugin_repositories: yes
          plugin_repositories_featured: The-Bocchette-2, Probability-Manager.js
          plugin_repositories_order: pinned, featured, starred
          plugin_repositories_pinned: 2
          plugin_repositories_starred: 2
          plugin_topics: yes
          plugin_topics_limit: 10
          plugin_topics_mode: labels
          plugin_topics_sort: starred
          plugin_traffic: yes
          plugin_traffic_skipped: Croc-Prog-github
          repositories_batch: 100
          repositories_forks: yes
          users_ignored: github-actions[bot]
